### ISSUE TITLE
BOTのトリガーとなるユーザー情報の保管DBとSQL文を活用したコードの作成

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.study#15]
今までギルド創設者が担当していた
ギルド内の整備を自動化する

ユーザーがDiscordでアクションした時間をDBに書き込む
その時間を元に、BOTが自動でメンバーに関する処理を行う
エンジンはDiscordのBOTが動くEC2内にインストールした
SQLiteを活用して作成することとする

# タスク
- [x] DBのテーブル・カラムの設計
- [ ] insert/update/の確認
- [x] jsコードからのSQL文正常動作確認
- [ ] Discordのメッセージ送信をトリガーにDBに書き込み確認

**Comment by supleiades** [comment]
まずは
- [x] 各メンバーのギルド参加datetimeを取得してinsertする処理を書く

**Comment by su-pleiades** [comment]
userid              username    modifeid_datetime    guild_join_datetime  voicechannel_lastjoin_datetime  voicechannel_lastleave_datetime  message_lastsent_datetime
------------------  ----------  -------------------  -------------------  ------------------------------  -------------------------------  -------------------------
603567991132782592  SuPleiades  2020-04-22 15:53:28

**Comment by supleiades** [comment]
- [ ] update処理の追加
- [ ] メッセージ送信者の情報のみを更新
