### ISSUE TITLE
タイマーほしい

### ISSUE THREAD

**Issue by tako-eng** [mo9mo9study/discord.study#16]
タイマーほしい（たまにカウントダウンしてくれたらなおうれしい）
!timer 120m
みたいな

**Comment by supleiades** [comment]
勉強会で3時間勉強する想定だけど
・１時間ごとに参加しているメンバーに経過時間を知らせるタイマー
・終了５分前に知らせるメッセージ
・終了時に終了メッセージと「勉強報告」のテンプレートを参加メンバーあてに送信する
