### ISSUE TITLE
discord.webに表示する勉強時間の実現方法検討

### ISSUE THREAD

**Issue by MasanoriIwakura** [mo9mo9study/discord.study#33]
# やりたいこと

discord.webに勉強時間を表示できるようにする

# 実現方法

discordのサーバー側で勉強時間を集計し、webの方から参照できるようにする必要がある

## 実現案

- REST APIを作る
- ファイル出力
→ファイル出力の方が難易度が楽

**Comment by floof-ball** [comment]
issue 検討ナイスです！
現状 Lightsail でしたっけ。

> REST APIを作る

APIサーバー用意する or LightsailをAPIサーバーに出来たりするのかな？
いずれにせよ、コストと応相談になりそうでしょうか？

> ファイル出力

MVCフレームワークなりに置き換えてサーバー側で集計する処理を書き、Viewに渡す。

のようなイメージですかね？

（DOM部分だけ置き換えたHTMLをgenerateして既存のHTMLと置き換えるってのもなくはないけど、最終手段感あるよね...）

**Comment by MasanoriIwakura** [comment]
@floof-ball 
現状EC2からLightsailに移行予定です！

Lightsailの場合は無茶な使い方をしなければコストは固定なので、気にしているのはAPIへのアクセス負荷です。

最悪はサーバー落ちますし、フロントからのアクセスを想定しているのでエンドポイント丸見えになるのでDDos攻撃も気にしています〜

**Comment by nntsugu** [comment]
横入り失礼します。
memcachedかRedisあたりのKVSに集計情報を載せておくのはいかがでしょう？
- 集計しKVSに投入するタイミングは
  - KVSに該当データがなかった(A) or データが有効期限切れ(Redisならexpireを設定することもできます)していた場合
  - KVS再起動後にバッチ処理(これは無くても良さそう)
- KVSにcacheしておけば、裏側のREST API or DBにアクセスしに行く頻度を減らせるので多少の攻撃的負荷はさばけると思います。*本気のDDoSならLightSail単体だとおそらく厳しいかなーと思います。アクセス元が少数ならACLで弾いたりできそうですが。

余談
- Redisは
  - 再起動時にデータが揮発しないようにすることもできる
  - 多少複雑なデータ構造をもたせることも可能→ランキング情報などを入れておくケースはよくあります。毎度計算する負荷から解放される。
- memcachedは
  - 単純なKey/Valueのみ対応
  - 再起動時にはデータが飛ぶので必要に応じてデータ投入が必要。上記(A)方式ならそこまで問題にならなさそう

さらに余談
- 集計処理リクエストをSQSに詰めて、Lambdaに順次処理させてKVSに投入させれば多数の集計リクエストがあってもLightSailのリソースを食いつぶしたりすることもないし平和になりそう。

**Comment by MasanoriIwakura** [comment]
一度要件を整理しますね。

## 現状

- ファイルに出力されたユーザーの勉強時間を日次、週次、月次で集計し、discordで通知
  - 集計結果を保持する仕組みが無い
  - ユーザー数は多く無いため、そんなに処理時間はかからないはず

## 今回やりたいこと

- ユーザーの勉強時間を日次、週次、月次で保持する仕組み
  - RDB等に保存するように修正が必要
- 上記で集計した勉強時間(全ユーザーの週、月の合計)を `discord.web` 側(GitHub Pages)で表示する仕組み
  - 集計時点でのユーザー数も表示したい！！

なので、大規模なことは考える必要が無くシンプルに
- 勉強時間を集計
- JSで勉強時間を取得し、画面に表示

ができればOKです！！

## 気にすべきこと

- WEBの表示数が増えるとJSからのリクエスト数が増えるため、コスト・セキュリティを意識する必要がある
- できればLightsailに直接アクセスされることは避けたい(セキュリティ面)

で、上記を踏まえると個人的には
- `discord.study` で勉強時間を集計
  - RDBに保存
  - 週次、月次でJSONファイルに出力し、S3にアップロード
- `discord.web` はJSからCloudFront経由でS3にアクセス

くらいのライトウェイトで良いと思っています！
ミドルウェアを増やすとコスト・管理コストが増えますし、考えることが増えるので！

**Comment by floof-ball** [comment]
@nntsugu @MasanoriIwakura 
検討ありがとうございます！（要件整理ありがとうございます、理解しました）

> discord.study で勉強時間を集計
> RDBに保存
> 週次、月次でJSONファイルに出力し、S3にアップロード
> discord.web はJSからCloudFront経由でS3にアクセス

賛成、構成良いと思います！
もし良ければ、具体的にフロント/バックエンドの処理を書く上で、技術的に考えていること（このようなアーキテクトにしたい、このようなライブラリ, フレームワークを使いたいなど）が既にあれば、そちらも後日お伺いしたいです！
