### ISSUE TITLE
discord.web用の勉強時間/参加メンバーの計算処理

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.study#55]
# 要件
- メンバーの参加人数
- 先月の全メンバーの勉強時間
- 先週の全メンバーの勉強時間

上記情報は「 https://mo9mo9study.github.io/discord.web/ 」ここの表示で使うため必要になる
そのため、いったんコマンドで簡単に出力できる様にしたい
※今後は一定間隔で動的にweb画面の表示が更新されたら嬉しい（週に１度更新とかレベルで）

**Comment by floof-ball** [comment]
https://github.com/mo9mo9study/discord.study/issues/33 と内容が似ているので linking
