### ISSUE TITLE
Wikiにコマンド一覧記載

### ISSUE THREAD

**Issue by yabutayukinari** [mo9mo9study/discord.study#80]
# 概要
とりあえずでBotの処理を増やしていっているが、
作った本人と管理者しか把握できていない可能性がある
機能一覧としてもあった方がいいかもしれないので、そろそろメンテナンスが必要そう

**Comment by supleiades** [comment]
別のリポジトリだけどこんな感じのREADME?
https://github.com/mo9mo9study/discord.CodeWarehouse/blob/master/node/README.md
一応写せるnodeの処理は移行完了

本格的にこちらのリポジトリを潰す（使わない）方向で進めていきたい。
